//! FR-P4-002 closure — Gate-A parity between Rust `PerSpecHMM` and the
//! ReSearch Python prototype.
//!
//! Loads the committed fixture at `tests/fixtures/gate_a/posterior.toml`
//! (generated by `scripts/export_gate_a_posterior.py`) and replays its
//! observable trace through the Rust filter. Asserts that the Rust tail
//! belief matches the Python prototype's within the FR-P4-002 2 pp
//! tolerance per cell.
//!
//! The fixture contains:
//!   - `specs`: spec IDs in the order the Python prototype enumerates them.
//!   - `supports.{id}`: file support sets (used to reconstruct `SpecDescriptor`).
//!   - `trace`: list of `{kind=write, files=[...]}` and
//!     `{kind=test, spec_id="..", outcome="pass"|"fail"}` events.
//!   - `expected.{id} = { p_unk, p_sat, p_vio, gt }`: prototype's final
//!     marginals + ground-truth status.
//!
//! The Rust `DefaultTestSensor` is the calibrated equivalent of the
//! prototype's `TestSensor` with default alphas — we assert the two
//! match to < 2 pp per cell after 120 steps / 324 events.

use std::collections::HashMap;

use ndarray::Array1;
use serde::Deserialize;
use specere_filter::hmm::SpecDescriptor;
use specere_filter::state::TestSensor;
use specere_filter::{drive::DefaultTestSensor, Motion, PerSpecHMM};

/// Separate sensor impl that deliberately mirrors the prototype formulas so
/// if `DefaultTestSensor` drifts we still anchor parity to the canonical
/// numbers. If this test fails but `DefaultTestSensor` tests still pass,
/// look here first.
struct ParitySensor;

const ALPHA_SAT: f64 = 0.92;
const ALPHA_VIO: f64 = 0.90;
const ALPHA_UNK: f64 = 0.55;
const EPS: f64 = 1e-6;

impl TestSensor for ParitySensor {
    fn log_likelihood(&self, _spec_id: &str, outcome: &str) -> Array1<f64> {
        let clip = |x: f64| x.max(EPS).ln();
        match outcome {
            "pass" => {
                ndarray::array![clip(ALPHA_UNK), clip(ALPHA_SAT), clip(1.0 - ALPHA_VIO)]
            }
            "fail" => {
                ndarray::array![
                    clip(1.0 - ALPHA_UNK),
                    clip(1.0 - ALPHA_SAT),
                    clip(ALPHA_VIO)
                ]
            }
            other => panic!("unexpected outcome in fixture: {other}"),
        }
    }
}

#[derive(Deserialize)]
struct Fixture {
    seed: u64,
    steps: u64,
    filter: String,
    specs: Vec<String>,
    supports: HashMap<String, Vec<String>>,
    trace: Vec<TraceEvent>,
    expected: HashMap<String, Expected>,
}

#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
enum TraceEvent {
    Write { files: Vec<String> },
    Test { spec_id: String, outcome: String },
}

#[derive(Deserialize)]
struct Expected {
    p_unk: f64,
    p_sat: f64,
    p_vio: f64,
    #[allow(dead_code)]
    gt: u8,
}

fn load_fixture() -> Fixture {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/gate_a/posterior.toml");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture at {}: {e}", path.display()));
    toml::from_str(&raw).expect("fixture TOML failed to parse")
}

#[test]
fn rust_perspec_hmm_matches_gate_a_fixture_within_2pp() {
    let fx = load_fixture();
    assert_eq!(fx.filter, "PerSpecHMM");
    assert_eq!(fx.seed, 0);
    assert_eq!(fx.steps, 120);

    // Build SpecDescriptors in fixture order.
    let specs: Vec<SpecDescriptor> = fx
        .specs
        .iter()
        .map(|id| SpecDescriptor {
            id: id.clone(),
            support: fx.supports.get(id).cloned().unwrap_or_default(),
        })
        .collect();

    let mut filter = PerSpecHMM::new(specs.clone(), Motion::prototype_defaults());
    let sensor = ParitySensor;

    for e in &fx.trace {
        match e {
            TraceEvent::Write { files } => {
                let refs: Vec<&str> = files.iter().map(|s| s.as_str()).collect();
                filter.predict(&refs);
            }
            TraceEvent::Test { spec_id, outcome } => {
                // `update_test` returns Err on unknown spec_id — the fixture
                // shouldn't contain such ids, so propagate as a panic.
                filter
                    .update_test(spec_id, outcome, &sensor)
                    .expect("fixture referenced an unknown spec id");
            }
        }
    }

    let mut max_diff = 0.0_f64;
    let mut worst = String::new();
    for (sid, expected) in &fx.expected {
        let actual = filter.marginal(sid).unwrap();
        let deltas = [
            (actual[0] - expected.p_unk).abs(),
            (actual[1] - expected.p_sat).abs(),
            (actual[2] - expected.p_vio).abs(),
        ];
        let d = deltas.iter().cloned().fold(0.0_f64, f64::max);
        if d > max_diff {
            max_diff = d;
            worst = format!(
                "{sid}: rust=[{:.4},{:.4},{:.4}] py=[{:.4},{:.4},{:.4}]",
                actual[0], actual[1], actual[2], expected.p_unk, expected.p_sat, expected.p_vio
            );
        }
    }
    eprintln!(
        "FR-P4-002 parity — max per-cell diff = {max_diff:.6} (tolerance 0.02); worst cell: {worst}"
    );
    assert!(
        max_diff < 0.02,
        "FR-P4-002 breach: max per-cell diff = {max_diff:.4} > 0.02\n  worst: {worst}"
    );
}

#[test]
fn default_test_sensor_matches_parity_sensor() {
    // Quick check that DefaultTestSensor hasn't drifted from the prototype
    // formulas. If this fails but the parity test still passes, the two
    // sensors diverged — fix whichever is wrong first.
    let default = DefaultTestSensor;
    let parity = ParitySensor;
    for outcome in ["pass", "fail"] {
        let a = default.log_likelihood("_", outcome);
        let b = parity.log_likelihood("_", outcome);
        for k in 0..3 {
            assert!(
                (a[k] - b[k]).abs() < 1e-12,
                "default vs parity divergence on outcome={outcome}[{k}]: {} vs {}",
                a[k],
                b[k]
            );
        }
    }
}
